name: test

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python 3.14
        run: uv python install 3.14
      - name: Run unit tests
        run: uv run pytest
